version: "2"

services:
  mysql:
    image: fdommp-db
    container_name: fd-db
    restart: always
    networks:
      - fd-net
    ports:
      - "3307:3306"
  redis:
    image: redis:3.2.8
    container_name: fd-redis
    command: redis-server
    expose:
       - "6379"
    networks:
      - fd-net
    depends_on:
      - mysql


  app:
    image: fdommp-app
    container_name: fd-app
    environment:
      FDOMMP_RUN_ENV: PROD
    volumes:
      - /root/Public/fdommp:/mnt/fdommp
    expose:
      - "8000"
    #ports:
    #  - "8090:8090"
    networks:
      - fd-net
    #links:
    #  - mysql
      #- redis
    command: bash /mnt/start.sh
    depends_on:
       - mysql
       - redis
    restart: always


  nginx:
    image: fdommp-nginx
    container_name: fd-nginx
    volumes:
      - /root/Public/fdommp:/mnt/fdommp
    ports:
      - "8080:80"
    networks:
      - fd-net
    #links:
    #  - app
    depends_on:
      - app
    restart: always

networks:
  fd-net:
    driver: bridge
